export const DASHBOARD_ADD_TEXT = 'Ajouter un texte'
export const DASHBOARD_TITLE_INFORMATION = 'Informations générales'
export const DASHBOARD_SHOW_HOME_INFORMATION = 'Afficher les informations sur la page d\'accueil'
export const DASHBOARD_TITLE_DATE = 'Date du festival :'
export const DASHBOARD_TITLE_GPS_COORDS = 'Coordonnées GPS :'
export const DASHBOARD_PLACEHOLDER_LATITUDE = 'latitude'
export const DASHBOARD_PLACEHOLDER_LONGITUDE = 'longitude'
export const DASHBOARD_SHOW_MUSICS = 'Afficher les musiques'
export const DASHBOARD_SHOW_MOVIES = 'Afficher les courts-métrages'

export const DASHBOARD_MODAL_NEW_TEXT_TITLE = 'Nouveau texte'
export const DASHBOARD_MODAL_TEXT = 'Entrez du texte'
export const DASHBOARD_MODAL_TEXT_RULE = 'Entrez du texte'
export const DASHBOARD_MODAL_TYPE = 'Type'
export const DASHBOARD_MODAL_TYPE_RULE = 'Entrez le type de texte'
