name: Codecov report 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  codecov:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set locale to fr_FR
      run: |
        sudo locale-gen fr_FR.UTF-8
        sudo update-locale LANG=fr_FR.UTF-8

    - name: Cache dependencies
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('./package-lock.json') }}-caching
        restore-keys: |
          node-modules-

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci

    - name: Run the tests
      run: npm test -- --coverage --passWithNoTests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
