name: Automatic Rebase on "/rebase"
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/rebase'
          reaction: eyes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Automatic Rebase
        uses: Teroneko-NET-Tools/action-auto-rebase@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}